version: "3"

services:
  frontend:
    build:
      context: .
#      context: https://github.com/AlexandrMaltsevYDX/countryside-style#main
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - dashboard_networks

networks:
  dashboard_networks:
    driver: bridge
